### ISSUE TITLE
Domain for sale?

### ISSUE THREAD

**Issue by SergioMendolia** [michaelb081988/rollforscenario#7]
Hey there, we love to use your website regularly for our games, but it seems the domain expired and is now parked for sale. Is there any way to access the github pages directly to continue using it?

**Comment by michaelb081988** [comment]
Page will be rewritten to work with default URLs for github pages, should be done in the next few days. Page URL will be https://michaelb081988.github.io/rollforscenario/ but this currently doesn't work.

**Comment by SergioMendolia** [comment]
Ah great thanks! But inbetween I rewrote the whole thing and hosted it on rollforscenar.io so I could add the brawlmachine scenarios and the upcoming Steamroller21 too.
